/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author shofiatul
 */
import backend.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FrmTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmTransaksi() {
        initComponents();
        showGoods();
        String[] cart = {"Nama Product","Harga"};
        tableCart.setModel(new DefaultTableModel(new Object[][] {},cart));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtCart = new javax.swing.JPanel();
        txtStore = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        btnDeleteCart = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        btnAddCart = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        txtProductDiJual = new javax.swing.JLabel();
        btnDeleteList = new javax.swing.JButton();
        btnBuyNow = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtCart.setBackground(new java.awt.Color(0, 153, 153));

        txtStore.setBackground(new java.awt.Color(153, 204, 255));
        txtStore.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        txtStore.setForeground(new java.awt.Color(255, 102, 102));
        txtStore.setText("Glowing  Semriwing Skincare");
        txtStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStoreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("Cart");

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCart);

        btnDeleteCart.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteCart.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnDeleteCart.setForeground(new java.awt.Color(255, 51, 51));
        btnDeleteCart.setText("Delete Cart");
        btnDeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCartActionPerformed(evt);
            }
        });

        btnSearchProduct.setBackground(new java.awt.Color(153, 204, 255));
        btnSearchProduct.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSearchProduct.setForeground(new java.awt.Color(255, 51, 51));
        btnSearchProduct.setText("Search Product");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnAddCart.setBackground(new java.awt.Color(153, 204, 255));
        btnAddCart.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnAddCart.setForeground(new java.awt.Color(255, 51, 51));
        btnAddCart.setText("Add Cart");
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        txtProductDiJual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtProductDiJual.setText("Product Di Jual");

        btnDeleteList.setBackground(new java.awt.Color(153, 204, 255));
        btnDeleteList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnDeleteList.setForeground(new java.awt.Color(255, 51, 51));
        btnDeleteList.setText("Delete List");
        btnDeleteList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteListActionPerformed(evt);
            }
        });

        btnBuyNow.setBackground(new java.awt.Color(153, 204, 255));
        btnBuyNow.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuyNow.setForeground(new java.awt.Color(255, 51, 51));
        btnBuyNow.setText("Buy Now");
        btnBuyNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyNowActionPerformed(evt);
            }
        });

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenjualanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablePenjualan);

        javax.swing.GroupLayout txtCartLayout = new javax.swing.GroupLayout(txtCart);
        txtCart.setLayout(txtCartLayout);
        txtCartLayout.setHorizontalGroup(
            txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtCartLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(txtCartLayout.createSequentialGroup()
                        .addGroup(txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtCartLayout.createSequentialGroup()
                                .addComponent(txtProductDiJual, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteList, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuyNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtCartLayout.createSequentialGroup()
                                .addComponent(btnDeleteCart, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddCart, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 7, Short.MAX_VALUE))))
        );
        txtCartLayout.setVerticalGroup(
            txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCartLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCart)
                    .addComponent(btnSearchProduct)
                    .addComponent(btnAddCart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductDiJual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyNow)
                    .addComponent(btnDeleteList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStoreActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnBuyNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyNowActionPerformed
        buyGoodsCart();
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnBuyNowActionPerformed

    private void btnDeleteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListActionPerformed
        showGoods();
    }//GEN-LAST:event_btnDeleteListActionPerformed

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
        try {
            getGoodsCart(txtSearch.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FrmTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCartActionPerformed
        DeleteOrCart();
    }//GEN-LAST:event_btnDeleteCartActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        try {
            searchGoods(txtSearch.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FrmTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void tableCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCartMouseClicked
        showGoods();
    }//GEN-LAST:event_tableCartMouseClicked

    private void tablePenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenjualanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePenjualanMouseClicked

    /**
     * @param args the command line arguments
     */
    public int pay;
    public void showGoods(){
        String[] kol = {"Nama Product","Harga"};
        ArrayList<Product> list = new Product().getAll();
        Object rowData[] = new Object[5];
        tablePenjualan.setModel(new DefaultTableModel(new Object[][] {},kol));
        for (Product pr : list){
            rowData[0] = pr.getNamaProduct();
            rowData[1] = pr.getHarga();
            ((DefaultTableModel)tablePenjualan.getModel()).addRow(rowData);
        }
    }
    
    public void DeleteOrCart(){
        String[] cart ={"Nama Product","Harga"};
        tableCart.setModel(new DefaultTableModel(new Object[][] {},cart));
        pay=0;
    }
    
    public void getGoodsCart(String namaProduct) throws SQLException  {
        String[] cart={"Nama Product","Harga"};
        DefaultTableModel kart=(DefaultTableModel)tableCart.getModel();
        ArrayList<Product> listProduct=new Product().search(namaProduct);
        Object buy[]=new Object[2];
        for (Product pr : listProduct){
            buy[0]=pr.getNamaProduct();
            buy[1]=pr.getHarga();
            pay+=pr.getHarga();
            ((DefaultTableModel)tableCart.getModel()).addRow(buy);
        }
    }
    
    public void buyGoodsCart(){
        String inp=JOptionPane.showInputDialog("Bayar : Rp."+pay);
        if(Integer.parseInt(inp)>=pay){
            JOptionPane.showMessageDialog(this, "Terima Kasih Telah Berbelanja Di Glowing Semriwing Skincare\n Kembalian anda = " + (Integer.parseInt(inp) - pay));
        }else{
            JOptionPane.showMessageDialog(this, "Pembayaran Kurang, Pembelian Dibatalkan");
        }
    }
    public void searchGoods(String namaProduct) throws SQLException {
        String[] cart={"Nama Product","Harga"};
        ArrayList<Product> listSkincare = new Product().search(namaProduct);
        Object rowData[] = new Object[4];
        tablePenjualan.setModel(new DefaultTableModel(new Object[][] {},cart));
        for (Product pr : listSkincare){
            rowData[0]=pr.getNamaProduct();
            rowData[1]=pr.getHarga();
            ((DefaultTableModel)tablePenjualan.getModel()).addRow(rowData);
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnBuyNow;
    private javax.swing.JButton btnDeleteCart;
    private javax.swing.JButton btnDeleteList;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tablePenjualan;
    private javax.swing.JPanel txtCart;
    private javax.swing.JLabel txtProductDiJual;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStore;
    // End of variables declaration//GEN-END:variables
}
